const expenseData = [
  {
    id: "1",
    icon: "cutlery",
    amount: 122,
    category: "Food & Drinks",
    subCategory: "Dinner",
    date: "08 May 25",
    mode: "Online",
  },
  {
    id: "2",
    icon: "rupee",
    amount: 422,
    category: "Food & Drinks",
    subCategory: "Lunch",
    date: "07 May 25",
    mode: "Cash",
  },
  {
    id: "3",
    icon: "bus",
    amount: 60,
    category: "Transport",
    subCategory: "Bus Fare",
    date: "06 May 25",
    mode: "Cash",
  },
  {
    id: "4",
    icon: "heartbeat",
    amount: 250,
    category: "Health",
    subCategory: "Medicine",
    date: "05 May 25",
    mode: "Online",
  },
  {
    id: "5",
    icon: "shopping-cart",
    amount: 1400,
    category: "Groceries",
    subCategory: "Monthly Shopping",
    date: "04 May 25",
    mode: "Card",
  },
  {
    id: "6",
    icon: "wifi",
    amount: 899,
    category: "Utilities",
    subCategory: "Internet",
    date: "03 May 25",
    mode: "Online",
  },
  {
    id: "7",
    icon: "film",
    amount: 250,
    category: "Entertainment",
    subCategory: "Movie",
    date: "02 May 25",
    mode: "UPI",
  },
  {
    id: "8",
    icon: "cutlery",
    amount: 180,
    category: "Food & Drinks",
    subCategory: "Snacks",
    date: "01 May 25",
    mode: "Cash",
  },
  {
    id: "9",
    icon: "book",
    amount: 500,
    category: "Education",
    subCategory: "Books",
    date: "30 April 25",
    mode: "Card",
  },
  {
    id: "10",
    icon: "tint",
    amount: 100,
    category: "Utilities",
    subCategory: "Water Bill",
    date: "29 April 25",
    mode: "Online",
  },
];

const investmentData = [
  {
    id: "1",
    icon: "line-chart",
    amount: 5000,
    category: "Mutual Fund",
    subCategory: "SIP - Axis Bluechip Fund",
    date: "08 May 25",
    mode: "Online",
  },
  {
    id: "2",
    icon: "bank",
    amount: 10000,
    category: "Fixed Deposit",
    subCategory: "HDFC Bank 1-Year FD",
    date: "07 May 25",
    mode: "Bank Transfer",
  },
  {
    id: "3",
    icon: "area-chart",
    amount: 2000,
    category: "Stocks",
    subCategory: "TCS Equity",
    date: "06 May 25",
    mode: "Online",
  },
  {
    id: "4",
    icon: "pie-chart",
    amount: 3000,
    category: "Mutual Fund",
    subCategory: "SBI Small Cap Fund",
    date: "05 May 25",
    mode: "UPI",
  },
  {
    id: "5",
    icon: "money",
    amount: 500,
    category: "Recurring Deposit",
    subCategory: "SBI RD Monthly",
    date: "04 May 25",
    mode: "Auto Debit",
  },
  {
    id: "6",
    icon: "inr",
    amount: 12000,
    category: "Public Provident Fund",
    subCategory: "PPF Deposit",
    date: "03 May 25",
    mode: "Net Banking",
  },
  {
    id: "7",
    icon: "diamond",
    amount: 15000,
    category: "Gold",
    subCategory: "Digital Gold Purchase",
    date: "02 May 25",
    mode: "Online",
  },
  {
    id: "9",
    icon: "file-text-o",
    amount: 6000,
    category: "Bonds",
    subCategory: "Government Bonds",
    date: "30 April 25",
    mode: "Online",
  },
  {
    id: "10",
    icon: "user-circle",
    amount: 8000,
    category: "NPS",
    subCategory: "National Pension Scheme",
    date: "29 April 25",
    mode: "Online",
  },
];

const incomeData = [
  {
    id: "1",
    icon: "briefcase",
    amount: 55000,
    category: "Salary",
    subCategory: "Monthly Salary - TCS",
    date: "01 May 25",
    mode: "Bank Transfer",
  },
  {
    id: "2",
    icon: "laptop",
    amount: 15000,
    category: "Freelance",
    subCategory: "Website Project - Client A",
    date: "03 May 25",
    mode: "UPI",
  },
  {
    id: "3",
    icon: "money",
    amount: 2000,
    category: "Selling",
    subCategory: "Sold Old Phone",
    date: "05 May 25",
    mode: "Cash",
  },
  {
    id: "4",
    icon: "university",
    amount: 3200,
    category: "Dividends",
    subCategory: "HDFC Mutual Fund Dividend",
    date: "07 May 25",
    mode: "Bank Transfer",
  },
  {
    id: "5",
    icon: "home",
    amount: 8000,
    category: "Rental Income",
    subCategory: "House Rent - May",
    date: "05 May 25",
    mode: "Online",
  },
  {
    id: "6",
    icon: "gift",
    amount: 500,
    category: "Cashback",
    subCategory: "Credit Card Cashback",
    date: "06 May 25",
    mode: "Card",
  },
  {
    id: "7",
    icon: "support",
    amount: 1000,
    category: "Gift",
    subCategory: "Birthday Gift",
    date: "09 May 25",
    mode: "Cash",
  },
  {
    id: "8",
    icon: "book",
    amount: 2500,
    category: "Teaching",
    subCategory: "Online Classes",
    date: "04 May 25",
    mode: "UPI",
  },
  {
    id: "9",
    icon: "car",
    amount: 3000,
    category: "Transport",
    subCategory: "Uber Driving",
    date: "02 May 25",
    mode: "Online",
  },
  {
    id: "10",
    icon: "globe",
    amount: 1800,
    category: "Content Creation",
    subCategory: "YouTube Ad Revenue",
    date: "08 May 25",
    mode: "Online",
  },
];

const outstandingData = [
  {
    id: "1",
    icon: "arrow-up", // You gave money
    amount: 3000,
    category: "Lent",
    subCategory: "Lent to Ramesh for rent",
    date: "02 May 25",
    mode: "Cash",
    status: "Pending",
  },
  {
    id: "2",
    icon: "arrow-down", // You owe money
    amount: 1500,
    category: "Borrowed",
    subCategory: "Borrowed from Suresh for grocery",
    date: "04 May 25",
    mode: "UPI",
    status: "Pending",
  },
  {
    id: "3",
    icon: "arrow-up",
    amount: 1000,
    category: "Lent",
    subCategory: "Lent to Ankit for travel",
    date: "01 May 25",
    mode: "Online",
    status: "Completed",
  },
  {
    id: "4",
    icon: "arrow-down",
    amount: 2000,
    category: "Borrowed",
    subCategory: "Borrowed from Dad for medical bills",
    date: "28 April 25",
    mode: "Cash",
    status: "Completed",
  },
  {
    id: "5",
    icon: "arrow-up",
    amount: 500,
    category: "Lent",
    subCategory: "Lent to office colleague",
    date: "06 May 25",
    mode: "UPI",
    status: "Pending",
  },
  {
    id: "6",
    icon: "arrow-down",
    amount: 750,
    category: "Borrowed",
    subCategory: "Took advance from friend for dinner",
    date: "07 May 25",
    mode: "Cash",
    status: "Pending",
  },
  {
    id: "7",
    icon: "arrow-up",
    amount: 1200,
    category: "Lent",
    subCategory: "Lent to cousin for shopping",
    date: "03 May 25",
    mode: "Card",
    status: "Pending",
  },
  {
    id: "8",
    icon: "arrow-down",
    amount: 1800,
    category: "Borrowed",
    subCategory: "Loan from Rahul for mobile recharge",
    date: "05 May 25",
    mode: "Online",
    status: "Completed",
  },
  {
    id: "9",
    icon: "arrow-up",
    amount: 2200,
    category: "Lent",
    subCategory: "Lent to friend for trip",
    date: "08 May 25",
    mode: "UPI",
    status: "Pending",
  },
  {
    id: "10",
    icon: "arrow-down",
    amount: 900,
    category: "Borrowed",
    subCategory: "Took loan from brother",
    date: "09 May 25",
    mode: "Cash",
    status: "Pending",
  },
];

export { expenseData, incomeData, investmentData, outstandingData };
