const incomeData = [
  {
    id: "1",
    icon: "briefcase",
    amount: 55000,
    category: "Salary",
    subCategory: "Monthly Salary - TCS",
    date: "01 May 25",
    mode: "Bank Transfer",
  },
  {
    id: "2",
    icon: "laptop",
    amount: 15000,
    category: "Freelance",
    subCategory: "Website Project - Client A",
    date: "03 May 25",
    mode: "UPI",
  },
  {
    id: "3",
    icon: "money",
    amount: 2000,
    category: "Selling",
    subCategory: "Sold Old Phone",
    date: "05 May 25",
    mode: "Cash",
  },
  {
    id: "4",
    icon: "university",
    amount: 3200,
    category: "Dividends",
    subCategory: "HDFC Mutual Fund Dividend",
    date: "07 May 25",
    mode: "Bank Transfer",
  },
  {
    id: "5",
    icon: "home",
    amount: 8000,
    category: "Rental Income",
    subCategory: "House Rent - May",
    date: "05 May 25",
    mode: "Online",
  },
  {
    id: "6",
    icon: "gift",
    amount: 500,
    category: "Cashback",
    subCategory: "Credit Card Cashback",
    date: "06 May 25",
    mode: "Card",
  },
  {
    id: "7",
    icon: "support",
    amount: 1000,
    category: "Gift",
    subCategory: "Birthday Gift",
    date: "09 May 25",
    mode: "Cash",
  },
  {
    id: "8",
    icon: "book",
    amount: 2500,
    category: "Teaching",
    subCategory: "Online Classes",
    date: "04 May 25",
    mode: "UPI",
  },
  {
    id: "9",
    icon: "car",
    amount: 3000,
    category: "Transport",
    subCategory: "Uber Driving",
    date: "02 May 25",
    mode: "Online",
  },
  {
    id: "10",
    icon: "globe",
    amount: 1800,
    category: "Content Creation",
    subCategory: "YouTube Ad Revenue",
    date: "08 May 25",
    mode: "Online",
  },
];

const outstandingData = [
  {
    id: "1",
    icon: "arrow-up", // You gave money
    amount: 3000,
    category: "Lent",
    subCategory: "Lent to Ramesh for rent",
    date: "02 May 25",
    mode: "Cash",
    status: "Pending",
  },
  {
    id: "2",
    icon: "arrow-down", // You owe money
    amount: 1500,
    category: "Borrowed",
    subCategory: "Borrowed from Suresh for grocery",
    date: "04 May 25",
    mode: "UPI",
    status: "Pending",
  },
  {
    id: "3",
    icon: "arrow-up",
    amount: 1000,
    category: "Lent",
    subCategory: "Lent to Ankit for travel",
    date: "01 May 25",
    mode: "Online",
    status: "Completed",
  },
  {
    id: "4",
    icon: "arrow-down",
    amount: 2000,
    category: "Borrowed",
    subCategory: "Borrowed from Dad for medical bills",
    date: "28 April 25",
    mode: "Cash",
    status: "Completed",
  },
  {
    id: "5",
    icon: "arrow-up",
    amount: 500,
    category: "Lent",
    subCategory: "Lent to office colleague",
    date: "06 May 25",
    mode: "UPI",
    status: "Pending",
  },
  {
    id: "6",
    icon: "arrow-down",
    amount: 750,
    category: "Borrowed",
    subCategory: "Took advance from friend for dinner",
    date: "07 May 25",
    mode: "Cash",
    status: "Pending",
  },
  {
    id: "7",
    icon: "arrow-up",
    amount: 1200,
    category: "Lent",
    subCategory: "Lent to cousin for shopping",
    date: "03 May 25",
    mode: "Card",
    status: "Pending",
  },
  {
    id: "8",
    icon: "arrow-down",
    amount: 1800,
    category: "Borrowed",
    subCategory: "Loan from Rahul for mobile recharge",
    date: "05 May 25",
    mode: "Online",
    status: "Completed",
  },
  {
    id: "9",
    icon: "arrow-up",
    amount: 2200,
    category: "Lent",
    subCategory: "Lent to friend for trip",
    date: "08 May 25",
    mode: "UPI",
    status: "Pending",
  },
  {
    id: "10",
    icon: "arrow-down",
    amount: 900,
    category: "Borrowed",
    subCategory: "Took loan from brother",
    date: "09 May 25",
    mode: "Cash",
    status: "Pending",
  },
];

export { incomeData, outstandingData };

export const actionsMessages = {
  expenseAddSuccess: "Successfully Added New Expense!",
  expenseAddError: "Unable to add expense!",
  investmentAddSuccess: "Successfully Added New Investment!",
  investmentAddError: "Unable to add investment!",
};
