const incomeData = [
  {
    id: "1",
    icon: "briefcase",
    amount: 55000,
    category: "Salary",
    subCategory: "Monthly Salary - TCS",
    date: "01 May 25",
    mode: "Bank Transfer",
  },
  {
    id: "2",
    icon: "laptop",
    amount: 15000,
    category: "Freelance",
    subCategory: "Website Project - Client A",
    date: "03 May 25",
    mode: "UPI",
  },
  {
    id: "3",
    icon: "money",
    amount: 2000,
    category: "Selling",
    subCategory: "Sold Old Phone",
    date: "05 May 25",
    mode: "Cash",
  },
  {
    id: "4",
    icon: "university",
    amount: 3200,
    category: "Dividends",
    subCategory: "HDFC Mutual Fund Dividend",
    date: "07 May 25",
    mode: "Bank Transfer",
  },
  {
    id: "5",
    icon: "home",
    amount: 8000,
    category: "Rental Income",
    subCategory: "House Rent - May",
    date: "05 May 25",
    mode: "Online",
  },
  {
    id: "6",
    icon: "gift",
    amount: 500,
    category: "Cashback",
    subCategory: "Credit Card Cashback",
    date: "06 May 25",
    mode: "Card",
  },
  {
    id: "7",
    icon: "support",
    amount: 1000,
    category: "Gift",
    subCategory: "Birthday Gift",
    date: "09 May 25",
    mode: "Cash",
  },
  {
    id: "8",
    icon: "book",
    amount: 2500,
    category: "Teaching",
    subCategory: "Online Classes",
    date: "04 May 25",
    mode: "UPI",
  },
  {
    id: "9",
    icon: "car",
    amount: 3000,
    category: "Transport",
    subCategory: "Uber Driving",
    date: "02 May 25",
    mode: "Online",
  },
  {
    id: "10",
    icon: "globe",
    amount: 1800,
    category: "Content Creation",
    subCategory: "YouTube Ad Revenue",
    date: "08 May 25",
    mode: "Online",
  },
];

export { incomeData };

export const actionsMessages = {
  expenseAddSuccess: "Successfully Added New Expense!",
  expenseAddError: "Unable to add expense!",
  investmentAddSuccess: "Successfully Added New Investment!",
  investmentAddError: "Unable to add investment!",
  outstandingsAddSuccess: "Successfully Added New Outstanding!",
  outstandingsAddError: "Unable to add outstandings!",
};

export const questionFlow = {
  initial: {
    question: "What do you want to add?",
    options: ["Expense", "Outstanding", "Investment", "Income"],
  },
  Expense: [
    { key: "description", question: "What did you spend on?" },
    { key: "amount", question: "How much did you spend?" },
    { key: "type", question: "Is it Personal or Business?" },
    { key: "isRecurring", question: "Is this a recurring expense?" },
    { key: "date", question: "What's the date of the expense?" },
  ],
  Income: [
    { key: "source", question: "What is the source of income?" },
    { key: "amount", question: "How much did you earn?" },
    { key: "date", question: "What's the date of the income?" },
  ],
  Investment: [
    { key: "investmentType", question: "What type of investment is this?" },
    { key: "amount", question: "How much did you invest?" },
    { key: "platform", question: "Where did you invest?" },
    { key: "date", question: "What's the investment date?" },
  ],
  Outstanding: [
    { key: "toWhom", question: "To whom is the outstanding amount?" },
    { key: "amount", question: "How much is the outstanding amount?" },
    { key: "dueDate", question: "What's the due date?" },
    { key: "category", question: "Is it rent, emi, loan, etc.?" },
  ],
};
