enum PaymentMode {
  CASH = "cash",
  ONLINE = "online",
  UPI = "upi",
  AUTO = "auto-debit",
  CARD = "card",
  NETBANKING = "net-banking",
  BANK = "bank",
}

enum Category {
  FOOD = "food",
  TRAVEL = "travel",
  SHOPPING = "shopping",
  UTILITIES = "utilities",
  HEALTH = "health",
  EDUCATION = "education",
  ENTERTAINMENT = "entertainment",
  SUBSCRIPTIONS = "subscriptions",
  INVESTMENT = "investment",
  LOAN = "loan",
  SAVINGS = "savings",
  FAMILY = "family",
  PETS = "pets",
  OTHER = "other",
}

enum SubCategory {
  GROCERIES = "groceries",
  RESTAURANTS = "restaurants",
  SNACKS = "snacks",
  COFFEE = "coffee",
  FUEL = "fuel",
  FLIGHT = "flight",
  TRAIN = "train",
  BUS = "bus",
  CAB = "cab",
  TOLLS = "tolls",
  CLOTHING = "clothing",
  ELECTRONICS = "electronics",
  HOME = "home-decor",
  GIFTS = "gifts",
  ELECTRICITY = "electricity",
  WATER = "water",
  INTERNET = "internet",
  MOBILE = "mobile",
  GAS = "cooking-gas",
  MEDICINES = "medicines",
  DOCTOR = "doctor",
  INSURANCE = "insurance",
  TUITION = "tuition",
  BOOKS = "books",
  COURSES = "courses",
  MOVIES = "movies",
  EVENTS = "events",
  GAMES = "games",
  OTT = "ott",
  SOFTWARE = "software",
  CLOUD = "cloud",
  STOCKS = "stocks",
  MUTUAL_FUNDS = "mutual-funds",
  CRYPTO = "crypto",
  FD = "fixed-deposit",
  EMI = "emi",
  PERSONAL_LOAN = "personal-loan",
  CREDIT_CARD = "credit-card",
  CHILDREN = "children",
  PARENTS = "parents",
  SPOUSE = "spouse",
  PET_FOOD = "pet-food",
  VET = "vet",
  GROOMING = "grooming",
  MISC = "miscellaneous",
}

enum CategoryIcon {
  FOOD = "food",
  AIRPLANE = "airplane",
  SHOPPING = "shopping",
  HEART_PULSE = "heart-pulse",
  MOVIE = "movie",
  SCHOOL = "school",
  YOUTUBE_SUBSCRIPTION = "youtube-subscription",
  CREDIT_CARD = "credit-card",
  PIGGY_BANK = "piggy-bank",
  GAMEPAD = "gamepad",
  WALLET = "wallet",
  LIGHTBULB = "lightbulb-on",
  FAMILY = "account-group",
  PET = "dog",
  HELP = "help-circle",
}

export { Category, CategoryIcon, PaymentMode, SubCategory };
